// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkBzK-H1LahDy_PNx0J4UCQEDmKDYmvAk',
    appId: '1:996284724714:ios:cbdaefba75dd9854f96e93',
    messagingSenderId: '996284724714',
    projectId: 'class-practice-app',
    storageBucket: 'class-practice-app.firebasestorage.app',
    iosBundleId: 'com.example.wsCube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiuSw-85M7nm8JRU-G9BKWu2g_51J1KMI',
    appId: '1:996284724714:web:0789e8879b7ba64bf96e93',
    messagingSenderId: '996284724714',
    projectId: 'class-practice-app',
    authDomain: 'class-practice-app.firebaseapp.com',
    storageBucket: 'class-practice-app.firebasestorage.app',
    measurementId: 'G-G0LVLPNSBE',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiuSw-85M7nm8JRU-G9BKWu2g_51J1KMI',
    appId: '1:996284724714:web:0789e8879b7ba64bf96e93',
    messagingSenderId: '996284724714',
    projectId: 'class-practice-app',
    authDomain: 'class-practice-app.firebaseapp.com',
    storageBucket: 'class-practice-app.firebasestorage.app',
    measurementId: 'G-G0LVLPNSBE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkBzK-H1LahDy_PNx0J4UCQEDmKDYmvAk',
    appId: '1:996284724714:ios:cbdaefba75dd9854f96e93',
    messagingSenderId: '996284724714',
    projectId: 'class-practice-app',
    storageBucket: 'class-practice-app.firebasestorage.app',
    iosBundleId: 'com.example.wsCube',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZGDU5Dsnfm98pAvQ6Mf8vF6YRO5vPw0',
    appId: '1:996284724714:android:e6d909b23d602548f96e93',
    messagingSenderId: '996284724714',
    projectId: 'class-practice-app',
    storageBucket: 'class-practice-app.firebasestorage.app',
  );

}